name: GitHub Actions Workflow
run-name: ${{ github.actor }} has started docker build workflow.
on:
  pull_request:
    types: [opened, edited, ready_for_review, synchronize]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
          build-args: 
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      
      - name: Run Docker container
        run: |
          docker run --rm \
            gptresearcher/gpt-researcher:latest \
            /bin/sh -c "pytest tests/all-6-report-types.py"