name: GitHub Actions Workflow
run-name: ${{ github.actor }} has started docker build workflow.
on:
  pull_request:
    types: [opened, edited, ready_for_review, synchronize]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      
      - name: Build Docker images
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
          
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      - name: Run tests with Docker Compose
        run: |
          docker-compose run --rm gpt-researcher-tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}